In [2]:
# четырёхмерный, пятимерный и более массив - это ТЕНЗОР

In [4]:
import numpy as np

In [6]:
data = [1, 2, 3, 4, 5]

arr = np.array(data)  # Создание из List

print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[1 2 3 4 5]
(5,)
int32
1


In [8]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2

array([1, 2, 3, 4, 5])

In [11]:
arr3 = np.array([1, 2, 3, 4, 5], dtype=np.float64)  # задаём явно тип данных

In [15]:
print(arr3)
print(arr3.shape)
print(arr3.dtype)
print(arr3.ndim)
print(len(arr3))
print(arr3.size)

[1. 2. 3. 4. 5.]
(5,)
float64
1
5
5


In [17]:
arr3 = arr3.astype(np.int64)  # приводим все элементы к типу int64

In [19]:
print(arr3)
print(arr3.dtype)

[1 2 3 4 5]
int64


In [23]:
arr4 = np.arange(0, 20, 1.5)
arr4  # в отличии от встроенной range(), arange() работает с дробными значениями

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5])

In [25]:
arr5 = np.linspace(0, 2, 5)
arr5

array([0. , 0.5, 1. , 1.5, 2. ])

In [27]:
arr5 = np.linspace(0, 2, 50)
arr5

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [31]:
random_array = np.random.random(5)
random_array  # мы сгенерировали 5 случайных значений от 0 до 1

array([0.798615  , 0.29874516, 0.74735931, 0.65391442, 0.80797695])

#### Диапазон случайных чисел от [a, b]: (b - a) * np.random() + a, где b > a

In [33]:
random_array = (10 - -5) * np.random.random(5) + -5
random_array

array([ 1.09281604,  3.97052972,  3.39740061, -3.25392286,  7.52726972])

#### Операции

In [36]:
arr = np.array([1, 2, 3, 4, 5])

arr1 = np.sin(arr)
print(arr1)

arr2 = np.cos(arr)
print(arr2)

arr3 = np.sqrt(arr)
print(arr3)

arr4 = np.log(arr)
print(arr4)

arr5 = np.exp(arr)
print(arr5)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [39]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [42]:
print(a + b)
print(np.add(a, b))

[ 7  9 11 13 15]
[ 7  9 11 13 15]


In [45]:
print(a * b)
print(np.multiply(a, b))

[ 6 14 24 36 50]
[ 6 14 24 36 50]


In [48]:
print(a - b)
print(np.subtract(a, b))

[-5 -5 -5 -5 -5]
[-5 -5 -5 -5 -5]


In [50]:
print(a / b)
print(np.divide(a, b))

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [52]:
arr = np.array([1, 2, 3, 4, 5])
print(arr * 2)
print(arr ** 2)

[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [97]:
arr = np.random.randint(-5, 10, 10)
arr

array([ 6, -4,  1,  9,  6,  2,  9,  1, -4,  5])

In [98]:
arr = np.random.randint(-10, 10, 10)
print(arr)

print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.sum())
print(arr.std())
print(np.median(arr))

[ -2 -10   5  -2  -2  -8   1   4  -9  -4]
5
-10
-2.7
-27
4.920365840057018
-2.0


In [99]:
arr < 2

array([ True,  True, False,  True,  True,  True,  True, False,  True,
        True])

In [100]:
arr

array([ -2, -10,   5,  -2,  -2,  -8,   1,   4,  -9,  -4])

In [95]:
arr = np.insert(arr, 2, -20)  # вставляем 20 в позицию 2
print(arr)

[  8  -9 -20  -3  -6   2   7   8   0   7   3   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0]


In [79]:
arr = np.delete(arr, 2)  # удаляем элемент во 2 позиции
print(arr)

[ 8 -9 -3 -6  2  7  8  0  7  3]


In [81]:
np.sort(arr)

array([-9, -6, -3,  0,  2,  3,  7,  7,  8,  8])

In [101]:
arr2 = np.array([0, 0, 0])

In [102]:
arr3 = np.concatenate((arr, arr2))
arr3  # конкатенировали (склеили массивы)

array([ -2, -10,   5,  -2,  -2,  -8,   1,   4,  -9,  -4,   0,   0,   0])

In [105]:
np.array_split(arr3, 3)  # array_split() позволяет разделить массив на колчество частей, указанных вторым аргументом

[array([ -2, -10,   5,  -2,  -2]),
 array([-8,  1,  4, -9]),
 array([-4,  0,  0,  0])]

In [107]:
arr = np.array([1, -2, 3, -4, 5])
arr[0] = 18
print(arr[2])

3


In [109]:
arr[0]

18

In [111]:
arr[0:2]

array([18, -2])

In [113]:
arr[::-1]

array([ 5, -4,  3, -2, 18])

In [115]:
arr[arr < 2]

array([-2, -4])

In [117]:
arr[(arr < 2) & (arr > 0)]

array([], dtype=int32)

In [119]:
arr[(arr < 4) | (arr > 0)]

array([18, -2,  3, -4,  5])

In [121]:
arr[1:4] = 0
arr

array([18,  0,  0,  0,  5])

In [126]:
matrix = np.array([(1, 2, 3), (4, 5, 6)], dtype=np.float64)
matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [128]:
matrix = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)

(3, 3)
2
9


In [134]:
matrix.reshape(1, 9)  # трансформируем в 1 строку и 9 столбцов

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [136]:
matrix = np.arange(1, 13).reshape(4, 3)
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [138]:
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [141]:
matrix2 = np.random.random((2, 2))
matrix2

array([[0.69000652, 0.38144328],
       [0.00418274, 0.45499259]])

In [149]:
print(matrix)
print()
matrix = np.resize(matrix, (4, 4))
print(np.resize('Game', (3, 3)))
print()
print(matrix)  # https://numpy.org/doc/stable/reference/generated/numpy.resize.html

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]

[['Game' 'Game' 'Game']
 ['Game' 'Game' 'Game']
 ['Game' 'Game' 'Game']]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [151]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [153]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [156]:
np.eye(4)  # единичная матрица 4-го порядка

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [161]:
np.full((4, 4), 21)  # заполняет матрицу значениями 21

array([[21, 21, 21, 21],
       [21, 21, 21, 21],
       [21, 21, 21, 21],
       [21, 21, 21, 21]])

In [173]:
np.empty((3, 4), dtype=np.int16)  # поправка на тип

array([[18752,   708,  -776,    48],
       [    0,     0,    17,     0],
       [    0,     0,     0,     0]], dtype=int16)

In [175]:
matrix = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

In [181]:
matrix3 = matrix.dot(matrix2)  # dot предлагает перемножать матрицы
print(matrix3)
print()
matrix4 = np.dot(matrix, matrix2)
print(matrix4)

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [184]:
matrix5 = matrix @ matrix2  # знак @ позволяет скалярно перемножать матрицы
matrix5

array([[19, 22],
       [43, 50]])

#### axis = 0 - ось cтрок, а axis = 1 - ось столбцов

In [189]:
matrix = np.arange(1, 10).reshape(3, 3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [191]:
np.delete(matrix, 1, axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [193]:
np.delete(matrix, 2, axis=1)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [195]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [197]:
np.sin(matrix)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [199]:
np.log(matrix)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [201]:
matrix.sum()

45

In [204]:
print(matrix.sum(axis=0))  # складываем элементы каждого столбца
print(matrix.sum(axis=1))  # складываем элементы каждой строки

[12 15 18]
[ 6 15 24]


In [206]:
matrix ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [208]:
matrix2 = matrix + 9

In [209]:
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [215]:
arr = np.concatenate((matrix, matrix2), axis=0)  # в строки превращаем и снизу добавляем
arr  # добавление в вертикальном направлении

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [218]:
arr = np.vstack((matrix, matrix2))  # добавляем строки
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [221]:
arr = np.hstack((matrix, matrix2))  # добавляем столбцы
arr

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [223]:
np.split(arr, 3)  # разбиваем матрицу на 3 шт.

[array([[ 1,  2,  3, 10, 11, 12]]),
 array([[ 4,  5,  6, 13, 14, 15]]),
 array([[ 7,  8,  9, 16, 17, 18]])]

In [225]:
np.split(arr, 3, axis=1)  # по столбцам

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[ 3, 10],
        [ 6, 13],
        [ 9, 16]]),
 array([[11, 12],
        [14, 15],
        [17, 18]])]

In [228]:
np.append(np.arange(1, 10), np.array([2, 4]))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 4])

In [230]:
matrix = np.arange(1, 10).reshape(3, 3)

In [232]:
matrix[1, 2]

6

In [233]:
matrix[2]

array([7, 8, 9])

In [234]:
matrix[:, 2]

array([3, 6, 9])

In [235]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [236]:
matrix[1:13, 0:2]

array([[4, 5],
       [7, 8]])

In [237]:
matrix[matrix > 5]

array([6, 7, 8, 9])

In [238]:
matrix.T  # транспонирование

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [240]:
matrix.flatten()  # возвращает матрицу превращённую в одну строку

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [241]:
np.linalg.inv(matrix)  # возвращает обратную матрицу

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [242]:
np.trace(matrix)  # след матрицы - это сумма её элементов главной диагонали

15

In [243]:
np.linalg.det(matrix)  # определитель матрицы

6.66133814775094e-16

In [244]:
np.linalg.matrix_rank(matrix)  # ранг матрицы

2

In [253]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)  # собственные числа и вектор
print(eigenvalues)
print(eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [254]:
# np.loadtxt('file.txt')  -> загрузка из текстового файла
# np.genfromtxt('file.csv', delimeter=', ')  -> загрузка из csv файла
# np.savetxt('file.txt', arr, delimeter=' ')  -> запись в текстовый файл
# np.savetxt('file.csv', arr, delimeter=', ')  -> запись в csv файл